version: '3.8'

services:
  spark-master:
    image: bitnami/spark:4.0.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"  
      - "7077:7077"  
    volumes:
      - ./notebooks:/opt/notebooks  
      - ./data:/opt/data            
      - ./scripts:/opt/scripts     
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    volumes:
      - ./notebooks:/opt/notebooks
      - ./data:/opt/data
      - ./scripts:/opt/scripts
    networks:
      - spark-network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-lab
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER=spark://spark-master:7077 
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./data:/home/jovyan/data            
      - ./scripts:/home/jovyan/scripts      
      - ./requirements.txt:/home/jovyan/requirements.txt 
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - spark-network

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9000:9000" 
      - "9001:9001" 
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data  # Persistir datos de MinIO
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge